// Shell Slide engine (pure, no React, no imports) — a Rush Hour-style sliding puzzle.
// 6×6 beach. The turtle (2 wide, row 2) must reach the ocean opening on the right edge.
// Logs slide along their length; rocks never move. One move = one slide of one piece,
// any distance. Levels are pre-generated by scripts/generateShellSlideLevels.mjs.

export const SIZE = 6;
export const EXIT_ROW = 2;
export const GOAL_OFFSET = SIZE - 2; // turtle touching the exit
const MAX_STATES = 60000;

// Level tiers by optimal move count. Level counts must match the generator's output.
export const TIERS = [
  { label: 'Easy',   count: 150, min: 3,  max: 7 },
  { label: 'Medium', count: 200, min: 8,  max: 12 },
  { label: 'Hard',   count: 250, min: 13, max: 18 },
  { label: 'Expert', count: 250, min: 19, max: 24 },
  { label: 'Master', count: 150, min: 25, max: 99 },
];
export const TOTAL_LEVELS = TIERS.reduce((n, t) => n + t.count, 0);

export function getDiff(levelNum) {
  let hi = 0;
  for (const t of TIERS) {
    hi += t.count;
    if (levelNum <= hi) return t;
  }
  return TIERS[TIERS.length - 1];
}

// Level encoding: "<pieces>|<rocks>|<optimal>". Each piece is 3 chars: type (h/H = horizontal
// length 2/3, v/V = vertical length 2/3), line (row or column), start offset. Piece 0 is the
// turtle. Rocks are cell indexes in base 36.
export function decodeLevel(str) {
  const [p, r, opt] = str.split('|');
  const pieces = [], start = [];
  for (let i = 0; i < p.length; i += 3) {
    const t = p[i];
    pieces.push({ horiz: t === 'h' || t === 'H', len: t === 'H' || t === 'V' ? 3 : 2, line: +p[i + 1], turtle: i === 0 });
    start.push(+p[i + 2]);
  }
  const rocks = [...r].map(ch => parseInt(ch, 36));
  return { pieces, rocks, start, optimal: +opt };
}

export function encodeLevel({ pieces, rocks, start, optimal }) {
  const p = pieces.map((pc, k) => (pc.horiz ? (pc.len === 3 ? 'H' : 'h') : (pc.len === 3 ? 'V' : 'v')) + pc.line + start[k]).join('');
  return `${p}|${rocks.map(i => i.toString(36)).join('')}|${optimal}`;
}

// Cells covered by a piece at offset `off`.
export function pieceCells(piece, off) {
  const out = [];
  for (let j = 0; j < piece.len; j++) {
    out.push(piece.horiz ? piece.line * SIZE + off + j : (off + j) * SIZE + piece.line);
  }
  return out;
}

export function occupancy(pieces, rocks, offs, skip = -1) {
  const occ = new Uint8Array(SIZE * SIZE);
  rocks.forEach(i => { occ[i] = 1; });
  pieces.forEach((p, k) => { if (k !== skip) pieceCells(p, offs[k]).forEach(i => { occ[i] = 1; }); });
  return occ;
}

// How far piece k can slide from its current offset: [minOffset, maxOffset].
export function slideRange(pieces, rocks, offs, k) {
  const occ = occupancy(pieces, rocks, offs, k);
  const p = pieces[k];
  const free = (off) => pieceCells(p, off).every(i => !occ[i]);
  let lo = offs[k], hi = offs[k];
  while (lo - 1 >= 0 && free(lo - 1)) lo--;
  while (hi + 1 + p.len <= SIZE && free(hi + 1)) hi++;
  return [lo, hi];
}

export const keyOf = (offs) => String.fromCharCode(...offs);

// Every board one slide away. Builds occupancy once and lifts each piece out in turn.
export function neighbors(pieces, rocks, offs) {
  const occ = occupancy(pieces, rocks, offs);
  const out = [];
  for (let k = 0; k < pieces.length; k++) {
    const p = pieces[k], off = offs[k];
    const step = p.horiz ? 1 : SIZE;
    const first = p.horiz ? p.line * SIZE + off : off * SIZE + p.line; // cell of the piece's start
    // Slide toward lower offsets: the cell just before the piece must be free.
    for (let o = off - 1, c = first - step; o >= 0 && !occ[c]; o--, c -= step) {
      const next = offs.slice(); next[k] = o; out.push(next);
    }
    // Slide toward higher offsets: the cell just past the piece's end must be free.
    for (let o = off + 1, c = first + p.len * step; o + p.len <= SIZE && !occ[c]; o++, c += step) {
      const next = offs.slice(); next[k] = o; out.push(next);
    }
  }
  return out;
}

// Fewest moves from `offs` to a solved board, plus the board after the first move:
// { moves, next } or null if unsolvable.
export function solveFrom(puzzle, offs) {
  const { pieces, rocks } = puzzle;
  if (offs[0] === GOAL_OFFSET) return { moves: 0, next: null };
  const startKey = keyOf(offs);
  const parent = new Map([[startKey, null]]);
  let frontier = [offs];
  for (let depth = 1; frontier.length && parent.size < MAX_STATES; depth++) {
    const nextFrontier = [];
    for (const s of frontier) {
      for (const n of neighbors(pieces, rocks, s)) {
        const key = keyOf(n);
        if (parent.has(key)) continue;
        parent.set(key, s);
        if (n[0] === GOAL_OFFSET) {
          let cur = n; // walk back to the board right after the start
          while (keyOf(parent.get(keyOf(cur))) !== startKey) cur = parent.get(keyOf(cur));
          return { moves: depth, next: cur };
        }
        nextFrontier.push(n);
      }
    }
    frontier = nextFrontier;
  }
  return null;
}

// 3 stars at optimal, 2 within half again as many moves, otherwise 1.
export function starsFor(moves, optimal) {
  if (moves <= optimal) return 3;
  if (moves <= Math.ceil(optimal * 1.5)) return 2;
  return 1;
}
